name: Deploy

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.23.0
      
      - name: Build and test with Docker Compose
        run: |
          docker compose build
          docker compose run backend pytest
      
      # Add deployment steps based on your hosting environment
